name: Java CI with Gradle

on: # Event
  push:
    branches: [ main, develop ] 
  pull_request:
    branches: [ main, develop ]

jobs: 
  test: # Job id
    runs-on: ubuntu-latest # Runner
    steps:
    - uses: actions/checkout@v2 # Step
    - name: Set up JDK 11 
      uses: actions/setup-java@v1
      with:
        java-version: 11 
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew --console verbose test jacocoTestReport jacocoTestCoverageVerification
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./build/reports/jacoco/test/jacocoTestReport.xml
