- name: Test with Gradle
  run: ./gradlew test
- name: Upload coverage to Codecov
  uses: codecov/codecov-action@v3
  with:
    token: ${{ secrets.CODECOV_TOKEN }}
    file: ./build/reports/jacoco/test/jacocoTestReport.xml
