name: Semantic Versioning

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install
      - name: Configure Git
        run: |
          git config --global user.email "wjdtmdcjf2gmail.com"
          git config --global user.name "middlefitting"
      - name: Run Standard-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: npx standard-version
      - uses: actions/checkout@v2
      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Bump version
        uses: qzb/standard-version@v1

#       - name: Create release
#         uses: actions/create-release@v1
#         with:
#           tag_name: v${{ env.RELEASE_VERSION }}
#           release_name: Release ${{ env.RELEASE_VERSION }}
#           body: |
#             ${{ env.CHANGELOG }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

